FROM node:20 AS builder

WORKDIR /app

ARG RESEND_API_KEY
ARG ADMIN_UID
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_PRIVATE_KEY
ARG FIREBASE_CLIENT_EMAIL
ARG ALLOWED_ORIGIN

ENV RESEND_API_KEY=$RESEND_API_KEY
ENV ADMIN_UID=$ADMIN_UID
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
ENV FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
ENV ALLOWED_ORIGIN=$ALLOWED_ORIGIN

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM gcr.io/distroless/nodejs20

WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["server.js"]
