name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app (if needed)
        run: npm run build

      - name: Set up SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set permissions for SSH key
        run: chmod 600 private_key.pem

      - name: Deploy to VPS
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no user@173.249.47.149 << 'EOF'
            cd /path/to/your/app
            git pull origin main  # Pull the latest changes from the repository
            npm install  # Install any new dependencies
            npm run build  # Build the app (if needed)
            pm2 restart strop  # Restart the app using pm2 (or your app manager)
          EOF
