import type { Metadata } from "next";
import localFont from "next/font/local";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Strop",
  description: "Generated by create next app",
};

const own_font = localFont({
  src: [
    {
      path: "/own_font/HelveticaNeueThin.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "/own_font/HelveticaNeueLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "/own_font/HelveticaNeueMedium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/own_font/HelveticaNeueRoman.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "/own_font/HelveticaNeueBold.otf",
      weight: "600",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <body className={own_font.className}>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
